# ---------- Build stage ----------

FROM node:16-alpine AS build

RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build

RUN yarn cache clean

# ---------- Runtime stage ----------

FROM node:16-alpine AS runtime

ENV NODE_ENV=production

WORKDIR /app

COPY package.json yarn.lock ormconfig.js ./

COPY --from=build /app/node_modules ./node_modules

COPY --from=build /app/dist ./dist

USER node

EXPOSE 5000

CMD ["node", "dist/main"]
